### ISSUE TITLE
Lógica de Registro en Backend

### ISSUE THREAD

**Issue by isfdyt80** [isfdyt80/PetBook#2]
**Detalles**: Implementar endpoints para el registro de usuarios. Usar bcrypt para encriptar la contraseña.

**Guardado en Base de Datos**: Insertar el nuevo usuario en la base de datos, asegurando unicidad del email.

-----
Extra
-----
**Detalles**: 
- Validar los campos de entrada en el frontend y en el backend para evitar datos incorrectos o vacíos.
- Hacer que el login permita ingresar solo si las credenciales son correctos, verificando los datos con PHP y MySQL.
- Agregar mensajes claros para los usuarios en caso de éxito o error.

**Bonus**: Incluir un botón de "Recuperar contraseña" y hacerlo funcional.

**Comment by JulianBarreiro** [comment]
(Front end: hay que asignar al formulario de registro de usuario la libreria bcrypt, utilizando jquery. Todo eso por parte del frontend.
